### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by rimager** [mapbox/analysis-demos#10]
I apologize in advance if this question is beyond the scope of what you could answer.

I see you use budo to serve the project. I do have it running locally under http://10.92.20.40:9967/

I would like to deploy this project to heroku but I am not sure how to edit package.json. Would you have any pointers for me? I doubt I should budo in Production.

Thanks,
Rima.

**Comment by caioiglesias** [comment]
Yes, budo is basically for prototyping. It is bundling the assets and index.html just reads the generated `bundle.js` file

I advise you to take a look at https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

And the sample repo https://github.com/heroku/node-js-getting-started

If you peek inside their `package.json`, you'll notice that their sample app runs `node index.js` when launched on the server. And inside `index.js` you'll see that the request handler renders `pages/index`. That would make you need to understand their templating engine.

Just to get the hang of it, instead of fiddling with templating, [deliver the `index.html` file at once](https://codeforgeek.com/2015/01/render-html-file-expressjs/).

**Comment by rimager** [comment]
That sounds like what I want to do, but I am having a hard time serving index.html on heroku, even locally :(

**Comment by rimager** [comment]
Oh so I need to use expressJS then. Thank you, I will give that a try!

**Comment by rimager** [comment]
@caioiglesias Thank you so much Caio. That was the solution!!
